FROM oven/bun:alpine

RUN apk update && apk add --no-cache shadow

RUN addgroup -S appgroup && adduser -S appgroup -G appgroup

USER appgroup

WORKDIR /app

COPY package*.json .
COPY bun.lockb .

RUN bun install

COPY . .

CMD [ "bun", "run", "dev" ]
