FROM oven/bun:alpine

# Install shadow package first
RUN apk update && apk add --no-cache shadow

# Create group and user separately for alpine
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup

USER appuser

WORKDIR /app

COPY package*.json .
COPY bun.lockb .

RUN bun install

COPY . .

RUN bun run build

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "bun", "run", "start" ]
